project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - about.qmd
    - index.qmd
    - analysis/01-data-loading.qmd
    - analysis/02-quality-control.qmd
    - analysis/03-normalisation.html
    - analysis/04-reduced-dimensions.html
    - analysis/05-clustering.html
    - analysis/06-cell-annotation.html
    - analysis/07-merge-samples.html
    - analysis/08-integrate-samples.html
  execute:
    message: false
    warning: false

knitr:
  opts_chunk: 
    message: false
    warning: false
    dev: "png"
    echo: true
    fig.align: "center"

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
    highlight: textmate
    df_print: paged
editor: visual

website:
  title: "Visium Spatial Transcriptomics"
  image: ""
  favicon: ""
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/zifornd/quarto-web
  page-footer:
    right:
      - icon: twitter
        href: https://twitter.com/zifornd
        aria-label: Zifo Twitter
      - icon: github
        href: https://github.com/zifornd
        aria-label: Zifo GitHub  
  navbar:
    background: light
    logo: quarto.png
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.html
      - text: "Analysis"
        menu:
          - text: "Data loading"
            href: analysis/01-data-loading.html
          - text: "Quality control"
            href: analysis/02-quality-control.html
          - text: "Normalization"
            href: analysis/03-normalization.html
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: "bug"
          - text: "FAQ"
            icon: "question-circle"
    right:
      - icon: twitter
        href: https://twitter.com/zifornd
        aria-label: Zifo Twitter
      - icon: github
        href: https://github.com/zifornd
        aria-label: Zifo GitHub

#bibliography: references.bib

# format:
#   html:
#     toc: true
#     theme: cosmo
#     css: styles.css
#     highlight: textmate
#     df_print: paged
author: "Ben Southgate"
date: now
# editor: visual
# message: false
# warning: false