project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - about.qmd
    - analysis/01-data-loading.qmd
    - analysis/02-quality-control.qmd
    - analysis/03-normalisation.qmd
    - analysis/04-reduced-dimensions.qmd
    - analysis/05-clustering.qmd
    - analysis/06-merge-samples.qmd
    - analysis/07-integrate-samples.qmd
    - analysis/08-marker-detection.qmd
    - analysis/09-fea-annotation.qmd
    - analysis/10-spatial-features.qmd
    - analysis/11-cell-atlas.qmd
  execute:
    message: false
    warning: false

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
    code-fold: show

editor: visual

website:
  title: "Visium Spatial Transcriptomics"
  image: ""
  favicon: ""
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/zifornd/quarto-web
  page-footer:
    right:
      - icon: twitter
        href: https://twitter.com/zifornd
        aria-label: Zifo Twitter
      - icon: github
        href: https://github.com/zifornd
        aria-label: Zifo GitHub  
  navbar:
    background: light
    logo: quarto.png
    collapse-below: lg
    left:
      - text: "Overview"
        href: about.html
      - text: "Analysis"
        menu:
          - text: "Data loading"
            href: analysis/01-data-loading.html
          - text: "Quality control"
            href: analysis/02-quality-control.html
          - text: "Normalisation"
            href: analysis/03-normalisation.html
          - text: "Reduced Dimensions"
            href: analysis/04-reduced-dimensions.html
          - text: "Clustering"
            href: analysis/05-clustering.html
          - text: "Merge-samples"
            href: analysis/06-merge-samples.html
          - text: "Integrate-samples"
            href: analysis/07-integrate-samples.html
          - text: "Marker-detection"
            href: analysis/08-marker-detection.html
          - text: "FEA Annotation"
            href: analysis/09-fea-annotation.html
          - text: "Spatially variable features"
            href: analysis/10-spatial-features.html
          - text: "Cell Atlas Annotation"
            href: analysis/11-cell-atlas.html
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: "bug"
            href: https://github.com/zifornd/.github/issues
          - text: "FAQ"
            icon: "question-circle"
            href: https://github.com/zifornd/visium

    right:
      - icon: twitter
        href: https://twitter.com/zifornd
        aria-label: Zifo Twitter
      - icon: github
        href: https://github.com/zifornd
        aria-label: Zifo GitHub

#bibliography: references.bib
author: "Ben Southgate"
date: now
